#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-

import sys, os
import misc
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_peewee.db import Database

from peewee import SqliteDatabase
from AppliWeb.models import Abonnements, Mails, Recherches
from AppliWeb import operations as op
from scraping import legifr_spider

app = Flask(__name__)
Bootstrap(app)
app.config.from_object('config')
db = Database(app)

import views, mail

reload(sys)
sys.setdefaultencoding("utf-8")

DATABASE = './pw_DDB.sqlite'
database = SqliteDatabase(DATABASE, threadlocals=True)

models.initialize()

# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    database.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not database.is_closed():
        database.close()

if __name__ == "__main__":
    app.run()
